---
- name: Create directory for extending systemd unit's configuration
  file:
    path: /etc/systemd/system/elasticsearch.service.d/
    state: directory

- name: Enable logging to systemd journal
  template:
    src: etc/systemd/system/elasticsearch.service.d/enable_journald.conf.j2
    dest: /etc/systemd/system/elasticsearch.service.d/enable_journald.conf
  notify:
    - Reload systemd configuration
    - Restart Elasticsearch

- name: Check if tuned service is enabled
  command: systemctl --quiet is-enabled tuned.service
  register: elasticsearch_tuned_service_res
  changed_when: false
  failed_when: false

- set_fact:
    elasticsearch_tuned_service_enabled: "{{ elasticsearch_tuned_service_res.rc == 0 }}"

- include_tasks: configure-tuned.yml
  when: elasticsearch_tuned_service_enabled

# NOTE: Elasticsearch recommends disabling swapping altogether for
# performance reasons. We opt for an approach that prevents swapping under
# normal circumstances, but still allows the OS to swap under emergency
# memory situations.
# For more details see:
# https://www.elastic.co/guide/en/elasticsearch/guide/current/heap-sizing.html
- name: Limit swapping to emergency memory situations
  sysctl:
    name: vm.swappiness
    value: 1
    sysctl_file: "{{ elasticsearch_sysctl_file }}"
  when: not elasticsearch_tuned_service_enabled

# NOTE: The minimal and maximal heap size is 256 MB and 31 GB (respectively)
# For more details see:
# https://www.elastic.co/guide/en/elasticsearch/guide/current/heap-sizing.html
- name: Set Heap size according to the desired fraction of total memory
  set_fact:
    elasticsearch_heap_size_mb: "{{ [[(ansible_memtotal_mb * elasticsearch_heap_size_mem_frac) | int, 256] | max, 31000] | min }}"

- name: Configure Elasticsearch
  template:
    src: etc/elasticsearch/elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
  notify:
    - Restart Elasticsearch

- name: Configure Elasticsearch system settings
  template:
    src: etc/sysconfig/elasticsearch.j2
    dest: /etc/sysconfig/elasticsearch
  notify:
    - Restart Elasticsearch

- block:
  - name: Configure Elasticsearch JVM options
    template:
      src: etc/elasticsearch/jvm.options.j2
      dest: /etc/elasticsearch/jvm.options
    notify:
      - Restart Elasticsearch

  - name: Configure Elasticsearch logging
    template:
      src: etc/elasticsearch/log4j2.properties.j2
      dest: /etc/elasticsearch/log4j2.properties
    notify:
      - Restart Elasticsearch

  - name: Remove other Elasticsearch logging configuration
    file:
      path: /etc/elasticsearch/logging.yml
      state: absent

  when: elasticsearch_version == "6"

- name: Enable Elasticsearch service
  systemd:
    name: elasticsearch
    enabled: yes
